// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum CpuidReg {
    Eax,
    Ebx,
    Ecx,
    Edx,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct FeatureWordInfo {
    pub func: u32,
    pub index: Option<u32>,
    pub reg: CpuidReg,
    pub names: &'static [&'static str; 32],
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CpuFeature {
    pub name: &'static str,
    pub func: u32,
    pub index: Option<u32>,
    pub reg: CpuidReg,
    pub bit: u8,
}

pub const FEATURE_WORDS: &[FeatureWordInfo] = &[
    FeatureWordInfo {
        func: 1,
        index: None,
        reg: CpuidReg::Edx,
        names: &[
            "fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "", "sep",
            "mtrr", "pge", "mca", "cmov", "pat", "pse36", "pn", "clflush", "", "ds", "acpi", "mmx",
            "fxsr", "sse", "sse2", "ss", "ht", "tm", "ia64", "pbe",
        ],
    },
    FeatureWordInfo {
        func: 1,
        index: None,
        reg: CpuidReg::Ecx,
        names: &[
            "pni",
            "pclmulqdq",
            "dtes64",
            "monitor",
            "ds-cpl",
            "vmx",
            "smx",
            "est",
            "tm2",
            "ssse3",
            "cid",
            "",
            "fma",
            "cx16",
            "xtpr",
            "pdcm",
            "",
            "pcid",
            "dca",
            "sse4.1",
            "sse4.2",
            "x2apic",
            "movbe",
            "popcnt",
            "tsc-deadline",
            "aes",
            "xsave",
            "osxsave",
            "avx",
            "f16c",
            "rdrand",
            "hypervisor",
        ],
    },
    FeatureWordInfo {
        func: 7,
        index: Some(0),
        reg: CpuidReg::Ebx,
        names: &[
            "fsgsbase",
            "tsc-adjust",
            "sgx",
            "bmi1",
            "hle",
            "avx2",
            "fdp-excp-only",
            "smep",
            "bmi2",
            "erms",
            "invpcid",
            "rtm",
            "cqm",
            "zero-fcs-fds",
            "mpx",
            "rdt-a",
            "avx512f",
            "avx512dq",
            "rdseed",
            "adx",
            "smap",
            "avx512ifma",
            "pcommit",
            "clflushopt",
            "clwb",
            "intel-pt",
            "avx512pf",
            "avx512er",
            "avx512cd",
            "sha-ni",
            "avx512bw",
            "avx512vl",
        ],
    },
    FeatureWordInfo {
        func: 7,
        index: Some(0),
        reg: CpuidReg::Ecx,
        names: &[
            "prefetchwt1",
            "avx512vbmi",
            "umip",
            "pku",
            "ospke",
            "waitpkg",
            "avx512vbmi2",
            "shstk",
            "gfni",
            "vaes",
            "vpclmulqdq",
            "avx512vnni",
            "avx512bitalg",
            "",
            "avx512-vpopcntdq",
            "",
            "la57",
            "",
            "",
            "",
            "",
            "",
            "rdpid",
            "",
            "kl",
            "bus-lock-detect",
            "cldemote",
            "",
            "sgx-lc",
            "pks",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 7,
        index: Some(0),
        reg: CpuidReg::Edx,
        names: &[
            "",
            "",
            "avx512-4vnniw",
            "avx512-4fmaps",
            "fsrm",
            "uintr",
            "",
            "",
            "",
            "",
            "md-clear",
            "",
            "",
            "",
            "serialize",
            "hybrid",
            "tsxldtrk",
            "",
            "pconfig",
            "arch-lbr",
            "ibt",
            "",
            "amx-bf16",
            "avx512-fp16",
            "amx-tile",
            "amx-int8",
            "spec-ctrl",
            "stibp",
            "flush-l1d",
            "arch-capabilities",
            "core-capabilities",
            "ssbd",
        ],
    },
    FeatureWordInfo {
        func: 7,
        index: Some(1),
        reg: CpuidReg::Eax,
        names: &[
            "",
            "",
            "",
            "",
            "avx-vnni",
            "avx512-bf16",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 0x80000001,
        index: None,
        reg: CpuidReg::Edx,
        names: &[
            "", "", "", "", "", "", "", "", "", "", "", "syscall", "", "", "", "", "", "", "", "",
            "nx", "", "mmxext", "", "", "fxsr-opt", "pdpe1gb", "rdtscp", "", "lm", "3dnowext",
            "3dnow",
        ],
    },
    FeatureWordInfo {
        func: 0x80000001,
        index: None,
        reg: CpuidReg::Ecx,
        names: &[
            "lahf-lm",
            "cmp-legacy",
            "svm",
            "extapic",
            "cr8legacy",
            "abm",
            "sse4a",
            "misalignsse",
            "3dnowprefetch",
            "osvw",
            "ibs",
            "xop",
            "skinit",
            "wdt",
            "",
            "lwp",
            "fma4",
            "tce",
            "",
            "nodeid-msr",
            "",
            "tbm",
            "topoext",
            "perfctr-core",
            "perfctr-nb",
            "",
            "pcx-l2i",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 0x80000008,
        index: None,
        reg: CpuidReg::Ebx,
        names: &[
            "clzero",
            "irperf",
            "xsaveerptr",
            "",
            "rdpru",
            "",
            "mcommit",
            "wbnoinvd",
            "",
            "amd-ibpb",
            "",
            "amd-ibrs",
            "amd-stibp",
            "",
            "amd-ibrs-always-on",
            "amd-stibp-always-on",
            "",
            "",
            "amd-ssbd",
            "virt-ssbd",
            "amd-no-ssb",
            "nscb",
            "psfd",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 0x80000021,
        index: None,
        reg: CpuidReg::Eax,
        names: &[
            "no-nested-data-bp",
            "",
            "lfence-always-serializing",
            "null-sel-clr-base",
            "",
            "",
            "auto-ibrs",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 0xd,
        index: Some(1),
        reg: CpuidReg::Eax,
        names: &[
            "xsaveopt", "xsavec", "xgetbv1", "xsaves", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        ],
    },
    FeatureWordInfo {
        func: 6,
        index: None,
        reg: CpuidReg::Eax,
        names: &[
            "digital-temp",
            "intel-turbo",
            "arat",
            "",
            "pln",
            "ecmd",
            "ptm",
            "hwp",
            "hwp-notify",
            "hwp-activity",
            "hwp-energy-performance",
            "hwp-request-pkg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    FeatureWordInfo {
        func: 0x8000000a,
        index: None,
        reg: CpuidReg::Edx,
        names: &[
            "npt",
            "lbrv",
            "svm-lock",
            "nripsave",
            "tsc-scale",
            "vmcb-clean",
            "flushbyasid",
            "decodeassists",
            "",
            "",
            "pause-filter",
            "",
            "pfthreshold",
            "avic",
            "",
            "v-vmsave-vmload",
            "vgif",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "vnmi",
            "",
            "sstep-filter",
            "",
            "",
            "",
        ],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_no_duplicate_names() {
        use std::collections::HashSet;
        let mut names = HashSet::new();
        for info in FEATURE_WORDS {
            for &name in info.names {
                if !name.is_empty() {
                    assert!(names.insert(name), "Duplicate feature name found: {}", name);
                }
            }
        }
    }
}
